---
# Cert tasks file for ansible-role-grafana-settings

- name: "Test if cert boolean variable is set correctly"
  ansible.builtin.assert:
    that:
      - cert is defined
      - cert is boolean
    quiet: yes

- name: "Get cert_file path from {{ grafana_config }}"
  ansible.builtin.shell:
    cmd: grep -E -i "^\s*cert_file\s" {{ grafana_config }}
  register: result

- name: "Set facts based on cert_file output"
  ansible.builtin.set_fact:
    cert_file_file: "{{ result.stdout.rsplit('/',1)[1] }}"
    cert_file_path: "{{ result.stdout.strip().split(' = ')[1].rsplit('/',1)[0] }}"
  when:
      - result.failed is false

- name: "Get cert_key path from {{ grafana_config }}"
  ansible.builtin.shell:
    cmd: grep -E -i "^\s*cert_key\s" {{ grafana_config }}
  register: result

- name: "Set facts based on cert_key output"
  ansible.builtin.set_fact:
    cert_key_file: "{{ result.stdout.rsplit('/',1)[1] }}"
    cert_key_path: "{{ result.stdout.strip().split(' = ')[1].rsplit('/',1)[0] }}"
  when:
      - result.failed is false

- name: "Upload Certificates to {{ inventory_hostname }}"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: '0400'
  with_items:
    - src: "{{ certificate_file }}"
      dest: "{{ cert_file_path }}/"
    - src: "{{ certificate_key }}"
      dest: "{{ cert_key_path }}/"
    - src: "{{ certificate_chain }}"
      dest: "{{ cert_file_path }}/"

- name: "Update {{ grafana_config }} with new Certificate files"
  ansible.builtin.lineinfile:
    dest: "{{ grafana_config }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    owner: root
    group: "{{ grafana_group }}"
    mode: '0640'
    state: present
    backup: yes
  with_items:
    - regexp: '^\s*cert_file\s'
      line: "cert_file = {{ cert_file_path }}/{{ certificate_file.rsplit('/', 1)[1] }}"
    - regexp: '^\s*cert_key\s'
      line: "cert_key = {{ cert_key_path }}/{{ certificate_key.rsplit('/', 1)[1] }}"
  notify: "Restart Grafana HTTP Server Daemon"
