---
# tasks file for ansible-role-grafana-settings

#- name: "Include OS-specific variables"
#  ansible.builtin.include_vars:
#    file: "{{ ansible_os_family }}.yaml"

#- name: "Gather the package facts"
#  ansible.builtin.package_facts:
#    manager: auto
#  when: ansible_facts.packages is not defined

- name: "Include tasks from cert playbook"
  ansible.builtin.include_tasks: cert.yaml